### ISSUE TITLE
comments in smart-charging.js  are inconsistent or misleading

### ISSUE THREAD

**Issue by mi-hol** [sebastiankb/wot-smart-charging#3]
line 43: 
// request each ~2s the ecar status and soc (7)
// (the timeout should be a little less than of the next function)

but line 50 
 // check each 5s, if eCar is ready to charge (8)
line  66:

, 2000); // update each 2s

Suggestion:

1. define constants for 'refresh wait timer' (like const CHARGE_POWER = 4000; // threshold for starting charge process)
2. derive the second wait time using a calculation involving 'refresh wait timer' if this is actually beneficial or needed as stated in comment

**Comment by sebastiankb** [comment]
Many thanks for the hint. I just updated the comment. 

The very simple application is just an example with the purpose to show how easily the data can be retrieved and actions can be invoked via WoT from different IoT instances. You are right, the smart charging application can be implemented in different ways and extended accordingly.

**Comment by mi-hol** [comment]
Thanks for this great and indeed excellent example showing ease of use!

Regarding the updated comments
Is the comment in line 44 actually correct? the code is now using identical 2s delay, which would still contradict the comment
