### ISSUE TITLE
are static TD files still needed in github?

### ISSUE THREAD

**Issue by mi-hol** [sebastiankb/wot-smart-charging#4]
a pull request on Jun 2, 2021 added dynamic TD file generation in pv-system.js but the static file pv-system.td.jsonld is still present.

```
// Save TD to an external file (needed for smart-charging.js)
fs.writeFile('pv-system.td.jsonld',
```

1. Is this file still needed? 
2. Would it be feasible & beneficial to convert all Thing js implementations to use dynamic TDs?

**Comment by sebastiankb** [comment]
Many thanks, for your request. 

>Is this file still needed?

The static version is only relevant to see what the potential TD looks like without running the application. 

> Would it be feasible & beneficial to convert all Thing js implementations to use dynamic TDs?

That depends on the use case. It makes sense, if the capabilities of Things change over time, that the latest capabilities are always reflected by the automatically generated TD and thus become available for consumer. Note that node-wot always generates the TD automatically when a WoT producer is started.
